export const FETCH_METAL_PRICES_REQUEST = 'FETCH_METAL_PRICES_REQUEST';
export const FETCH_METAL_PRICES_SUCCESS = 'FETCH_METAL_PRICES_SUCCESS';
export const FETCH_METAL_PRICES_FAILURE = 'FETCH_METAL_PRICES_FAILURE';

export const UPDATE_METAL_PRICE_REQUEST = 'UPDATE_METAL_PRICE_REQUEST';
export const UPDATE_METAL_PRICE_SUCCESS = 'UPDATE_METAL_PRICE_SUCCESS';
export const UPDATE_METAL_PRICE_FAILURE = 'UPDATE_METAL_PRICE_FAILURE';

export const CLEAR_METAL_PRICE_ERRORS = 'CLEAR_METAL_PRICE_ERRORS';
