export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_2FA_REQUIRED = 'LOGIN_2FA_REQUIRED';
export const VERIFY_2FA_REQUEST = 'VERIFY_2FA_REQUEST';
export const VERIFY_2FA_SUCCESS = 'VERIFY_2FA_SUCCESS';
export const VERIFY_2FA_FAILURE = 'VERIFY_2FA_FAILURE';
export const RESEND_2FA_REQUEST = 'RESEND_2FA_REQUEST';
export const RESEND_2FA_SUCCESS = 'RESEND_2FA_SUCCESS';
export const RESEND_2FA_FAILURE = 'RESEND_2FA_FAILURE';
export const LOGOUT = 'LOGOUT';
export const INITIALIZE_AUTH = 'INITIALIZE_AUTH';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

