export const FETCH_PROMOCODES_REQUEST = 'FETCH_PROMOCODES_REQUEST';
export const FETCH_PROMOCODES_SUCCESS = 'FETCH_PROMOCODES_SUCCESS';
export const FETCH_PROMOCODES_FAILURE = 'FETCH_PROMOCODES_FAILURE';

export const FETCH_PROMOCODE_REQUEST = 'FETCH_PROMOCODE_REQUEST';
export const FETCH_PROMOCODE_SUCCESS = 'FETCH_PROMOCODE_SUCCESS';
export const FETCH_PROMOCODE_FAILURE = 'FETCH_PROMOCODE_FAILURE';

export const CREATE_PROMOCODE_REQUEST = 'CREATE_PROMOCODE_REQUEST';
export const CREATE_PROMOCODE_SUCCESS = 'CREATE_PROMOCODE_SUCCESS';
export const CREATE_PROMOCODE_FAILURE = 'CREATE_PROMOCODE_FAILURE';

export const UPDATE_PROMOCODE_REQUEST = 'UPDATE_PROMOCODE_REQUEST';
export const UPDATE_PROMOCODE_SUCCESS = 'UPDATE_PROMOCODE_SUCCESS';
export const UPDATE_PROMOCODE_FAILURE = 'UPDATE_PROMOCODE_FAILURE';

export const DELETE_PROMOCODE_REQUEST = 'DELETE_PROMOCODE_REQUEST';
export const DELETE_PROMOCODE_SUCCESS = 'DELETE_PROMOCODE_SUCCESS';
export const DELETE_PROMOCODE_FAILURE = 'DELETE_PROMOCODE_FAILURE';

export const TOGGLE_PROMOCODE_STATUS_REQUEST = 'TOGGLE_PROMOCODE_STATUS_REQUEST';
export const TOGGLE_PROMOCODE_STATUS_SUCCESS = 'TOGGLE_PROMOCODE_STATUS_SUCCESS';
export const TOGGLE_PROMOCODE_STATUS_FAILURE = 'TOGGLE_PROMOCODE_STATUS_FAILURE';

export const CLEAR_PROMOCODE_ERRORS = 'CLEAR_PROMOCODE_ERRORS';

