export const FETCH_CUSTOMIZATION_REQUESTS_REQUEST = 'FETCH_CUSTOMIZATION_REQUESTS_REQUEST';
export const FETCH_CUSTOMIZATION_REQUESTS_SUCCESS = 'FETCH_CUSTOMIZATION_REQUESTS_SUCCESS';
export const FETCH_CUSTOMIZATION_REQUESTS_FAILURE = 'FETCH_CUSTOMIZATION_REQUESTS_FAILURE';

export const FETCH_CUSTOMIZATION_REQUEST_REQUEST = 'FETCH_CUSTOMIZATION_REQUEST_REQUEST';
export const FETCH_CUSTOMIZATION_REQUEST_SUCCESS = 'FETCH_CUSTOMIZATION_REQUEST_SUCCESS';
export const FETCH_CUSTOMIZATION_REQUEST_FAILURE = 'FETCH_CUSTOMIZATION_REQUEST_FAILURE';

export const PROCESS_ORDER_REQUEST = 'PROCESS_ORDER_REQUEST';
export const PROCESS_ORDER_SUCCESS = 'PROCESS_ORDER_SUCCESS';
export const PROCESS_ORDER_FAILURE = 'PROCESS_ORDER_FAILURE';

export const CLEAR_CUSTOMIZATION_REQUEST_ERRORS = 'CLEAR_CUSTOMIZATION_REQUEST_ERRORS';

